export default {
  string_string: '@string',
  string_email: '@email',
  string_phone: '@phone',
  string_username: '@cname',
  string_url: '@url',
  string_uuid: '@guid',
  string_id: '@increment',
  string_status: '@status',
  string_authority: '@authority',
  string_label: '@label',
  string_group: '@group',
  string_csentence: '@csentence',
  string_cname: '@cname',
  string_name: '@last',
  string_errorCode: '@increment',
  string_country: '@country',
  string_county: '@county(true)',
  string_province: '@province',
  string_city: '@city',
  string_avatar: '@avatar',
  string_href: '@href',
  'string_string(16)': 'string(16)',
  'string_date-time': '@datetime',
  string_date: '@date',

  string_total_records: '@integer(60, 100)',
  string_page_index: 1,
  string_page_size: '@integer(1, 10)',

  number: '@integer(60, 100)',
  number_float: '@float(60, 100, 3, 5)',
  integer: '@integer(60, 100)',
  boolean: '@boolean',
};
